### ISSUE TITLE
How to compute lexical overlap (F1 measured between two bags of words)?

### ISSUE THREAD

**Issue by YJiangcm** [princeton-nlp/SimCSE#102]
Thanks for your excellent job. In section 4 of the paper, you compute the lexical overlap (F1 measured between two bags of words) for the entailment pairs (SNLI + MNLI) is 39%, while they are 60% and 55% for QQP and ParaNMT. I wonder if _two bag of words_ means using window slice of 2? And how to define true posotive, true negative, false positive and false negative to compute the F1 score?

**Comment by gaotianyu1350** [comment]
Hi,

Here we use the same way of calculating F1 as in question answering tasks. It's simply unigram, not bigram. For each sentence, you have a bag of words, and true positive would be the words that are at the intersection of both sets.

**Comment by YJiangcm** [comment]
Got it, thx!
