### ISSUE TITLE
Is the BertModel's pooler parameters (the linear matrics) trained in the unsupervised training process?

### ISSUE THREAD

**Issue by HamLaertes** [princeton-nlp/SimCSE#109]
Hi,
Thanks for your awesome work. I have a detail question.
In the training process, the cls.pooler seems not to use the the pooler_outputs from the BertModel. As you can see from the following code, both the pooler_type 'cls_before_pooler' and 'cls' return the last_hidden[:, 0], **thus the linear parameters in the BertModel's pooler isn't optimized during the training process**:
```    def forward(self, attention_mask, outputs):
        last_hidden = outputs.last_hidden_state
        pooler_output = outputs.pooler_output
        hidden_states = outputs.hidden_states

        if self.pooler_type in ['cls_before_pooler', 'cls']:
            return last_hidden[:, 0]
        elif ...
        ...
```
However, in the evaluation.py, the code writes:
```
        with torch.no_grad():
            outputs = model(**batch, output_hidden_states=True, return_dict=True)
            last_hidden = outputs.last_hidden_state
            pooler_output = outputs.pooler_output
            hidden_states = outputs.hidden_states

        # Apply different poolers
        if args.pooler == 'cls':
            # There is a linear+activation layer after CLS representation
            return pooler_output.cpu()
        elif args.pooler == 'cls_before_pooler':
            return last_hidden[:, 0].cpu()
        ...
```
**The batcher function returns the pooler_ouput from the BertModel to the eval engine when pooler_type is "cls". But the linear parameters in the BertModel's pooler isn't optimized in the training process.**

This seems strange to me. Do i misunderstand the above implementations? It's very nice if you can help me find it out~

**Comment by yangzhaopeng3** [comment]
> Hi,
> 
> The original MLP head is not used in training. Instead we set our own MLP head as ` cls.pooler` (this is simply for implementation flexibility). But in the test time, we convert our own MLP to the original MLP in `simcse_to_huggingface.py` (so that you can easily use it in MLP).

Hi  Tianyu, @gaotianyu1350 

Thanks for your excellent work!

I have the same question of this problem, and after browsing the similar issues, I want to check if I am thinking correct about this question.

1. When training **unsupervised** models, we need to set `mlp_only_train=True`, so **during the training process**, training would use the [CLS] token embedding **after** MLP, while evaluating the model (in the training process) would directly using the [CLS] token embedding **before** the MLP layer. While training the **supervised** one using [CLS] token embedding **after** MLP layer all the time.
2. When the training process ends, we can use the `simcse_to_huggingface.py` to convert the customized MLP used in training to the original one in the BertModel. So in `evaluation.py`, no explicit operation like `cls.MLP()`  is needed, as the MLP used in training has been integrated to the BertModel. And `cls_before_pooler` for unsup. and `cls` for sup. models.

Am I thinking right?

Thanks for your reply. Have a nice day.

**Comment by gaotianyu1350** [comment]
Hi,

Yes your understanding is correct.
