### ISSUE TITLE
Is there  an experiment using 2(N-1) examples as negative examples 

### ISSUE THREAD

**Issue by 051548** [princeton-nlp/SimCSE#11]
Hello, Good Job!

I have a  question:

Is there an experiment using 2(N-1) examples as negative examples in unsupervised SimCSE? Maybe more negative samples in one batch can get an improvement;

thanks;

**Comment by gaotianyu1350** [comment]
Hi,

Good question! We have tried this, and there is no significant difference between using N-1 and 2N-1. For efficiency issues, we just use N-1 in our final model.

**Comment by 051548** [comment]
Got it; Thank you for your reply;
