### ISSUE TITLE
Save and load model.build_index results

### ISSUE THREAD

**Issue by visualcomments** [princeton-nlp/SimCSE#117]
Hello, 
I often use a large data for sentences and if it is possible I prefer to work with saved indexes. 
Could you tell me is it possible to save (write) the result of indexing the sentences (I'm using faiss-cpu version of  `model.build_index(sentences)` ) and after that load (read) it as model index? 
Thank you in advance!

**Comment by gaotianyu1350** [comment]
Hi,

You can check out [this line of code](https://github.com/princeton-nlp/SimCSE/blob/2adbdb3df3c4a6ef4d62edc283e5f1b6d07e3026/simcse/tool.py#L121). If you want to save/load model index, you can modify this part of code.

**Comment by visualcomments** [comment]
> You can check out [this line of code](https://github.com/princeton-nlp/SimCSE/blob/2adbdb3df3c4a6ef4d62edc283e5f1b6d07e3026/simcse/tool.py#L121). If you want to save/load model index, you can modify this part of code.
Thank you for answering! As I understood, I should put inside this code something like `faiss.write_index(index, "my.index")` and `index = faiss.read_index("my.index")`.
But I'm not quite experienced in editing the code. Could you suggest where exactly should I put this code?

**Comment by gaotianyu1350** [comment]
You can just add the code in the function I pointed out above. Loading the index at the beginning of the function if there exists one; writing the index at the end of the function.

**Comment by visualcomments** [comment]
Thank you for details! It's much clearer now.
