### ISSUE TITLE
How to add values into tensorboard recorders？

### ISSUE THREAD

**Issue by marscrazy** [princeton-nlp/SimCSE#119]
Thanks for your great works. It's a very simple and effective method to encode sentences.
I try to record some values during the training process, such as the loss term. But I cannot find the code like the SummaryWriter in tensorboardx. Could you tell me which file or function I should look for?

**Comment by gaotianyu1350** [comment]
Hi,

Our code is based on Huggingface's [transformers](https://github.com/huggingface/transformers), where they have already integrated tensorboard support in [trainer.py](https://github.com/huggingface/transformers/blob/master/src/transformers/trainer.py).

**Comment by marscrazy** [comment]
Thanks.
