### ISSUE TITLE
Questions about align and uniform

### ISSUE THREAD

**Issue by chaochen99** [princeton-nlp/SimCSE#122]
Hi,
We use the following code in the paper **Understanding Contrastive Representation Learning through Alignment and Uniformity on the Hypersphere** to calculate align and uniform.

    def lalign(x, y, alpha=2):
              return (x - y).norm(dim=1).pow(alpha).mean()
    def lunif(x, t=2):
              sq_pdist = torch.pdist(x, p=2).pow(2)
              return sq_pdist.mul(-t).exp().mean().log()

but the align_loss I get is several hundred, such as 

      align_loss:184.97857666015625
      uniform_loss:-5.186542987823486

I would like to know if you use this formula to calculate align and uniform, and whether the result is scaled in the end?

Looking forward to your reply.

**Comment by gaotianyu1350** [comment]
Hi,

When using this code, you should normalize x and y before the calculation. I assume the huge alignment score is due to that you didn't normalize it.
