### ISSUE TITLE
reproduce

### ISSUE THREAD

**Issue by sunersheng** [princeton-nlp/SimCSE#123]
hello, I can't reproduce the results reported in your paper and don't know why,can you tell me the reason and the training details. I train the model based on bert-base-uncased model  and get avg, 75.7~76.0 compared with your result 76.25.

**Comment by sunersheng** [comment]
> hello, I can't reproduce the results reported in your paper and don't know why,can you tell me the reason and the training details. I train the model based on bert-base-uncased model and get avg, 75.7~76.0 compared with your result 76.25.

I tried different weight initialization such as He and Xaxiver on the MLP on the top of [CLS].

**Comment by gaotianyu1350** [comment]
Hi,

Results can vary based on different hardware/software (our readme provides the hardware/software that we used). 76% sounds close enough to me if using different seeds/hardware/software.

**Comment by Nicola-Zhang** [comment]
> hello, I can't reproduce the results reported in your paper and don't know why,can you tell me the reason and the training details. I train the model based on bert-base-uncased model and get avg, 75.7~76.0 compared with your result 76.25.

I also encountered the same problem, and the results were quite different.
