### ISSUE TITLE
Query embedding will have change after each time do it again?

### ISSUE THREAD

**Issue by tampt9** [princeton-nlp/SimCSE#124]
Hi, query embedding vector will have change after each time do it again?

**Comment by gaotianyu1350** [comment]
Hi,

Can you be more specific about the issue? Which query embedding were you talking about?

**Comment by tampt9** [comment]
> 

Hi,
When I run model.build_index() function, I save embedding vector space in pickle file . After that, I load file pickle into model.search() function and put a query to search. So the result have big different  in case using pickle  file and don't use pickle file. 
Then, I check vector of query with many time encode, I saw vector of query change. So, why is that?

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for reporting this. Can you paste the code here and also your environment? Did the randomness happen only with the pickle or even with the online case?

**Comment by binhetech** [comment]
@gaotianyu1350 hi，same questions for me. The cosine similarity have change after each time do it again after loaded model. Could you help me to solve it?

model = SimCSE("../model/bert-base-cased/checkpoint-4500")
sentences_a = ['A woman is reading.', 'A man is playing a guitar.']
sentences_b = ['He plays guitar.', 'A woman is making a photo.']
similarities = model.similarity(sentences_a, sentences_b)

**Comment by gaotianyu1350** [comment]
Hi,

I tried the above script on both CPU and GPU (3090) and the results are the same. Can you check your pytorch and transformers versions and see whether they match the requirements.txt?

**Comment by binhetech** [comment]
ok, thanks, i have checked the pytorch(1.7.1) and transformers(4.2.1) versions, it seems to be consistent. After trained model, and load model to predict, it shows info below: Some weights of BertModel were not initialized from the model checkpoint at ../model/bert-base-cased/checkpoint-4500 and are newly initialized: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias'].  Is this wright? @gaotianyu1350

**Comment by gaotianyu1350** [comment]
Hi,

If you are using your own trained model, you should convert them to the huggingface format (see the Convert models part in readme)

**Comment by binhetech** [comment]
Hi, it's ok and After convert model to the huggingface format, the results is same. Thanks so much!
