### ISSUE TITLE
Information retrieval

### ISSUE THREAD

**Issue by tampt9** [princeton-nlp/SimCSE#125]
Hi,
I am having a plan for using SimCSE to IR problems (question, document). With input is a question, I will find the most relevant sentence, then I will get the document that contains the anwser for that question. What do you think about this plan? Can you help me share a few differences bewteen SimCSE in case and IR models? Thank you very much.

**Comment by gaotianyu1350** [comment]
Hi,

The biggest difference is that SimCSE is applied to sentences, while IR usually encodes both questions (sentence) and documents (asymmetric). Your plan sounds legit.
