### ISSUE TITLE
How do you implement your dropout method in unsupervised setting? And do you apply any dropout in the supervised setting?

### ISSUE THREAD

**Issue by KawaiiNotHawaii** [princeton-nlp/SimCSE#126]
I didn't find how you apply dropout in the unsupervised setting on the glance at the code. Would you mind directly navigating me to the implementation code on this?
Besides, did you apply dropout when doing supervised contrastive learning using the NLI dataset?
Thanks a lot.

**Comment by gaotianyu1350** [comment]
Hi,

Our model simply uses standard dropout from the transformer model, which is implemented in the `transformers` package. We also use dropout in the NLI dataset, as dropout is part of the standard training procedure.
