### ISSUE TITLE
Unsupervised dropout method 

### ISSUE THREAD

**Issue by yukyunglee** [princeton-nlp/SimCSE#127]
Hi,

First of all, thanks for the excellent research. The idea of the paper was interesting, and the experiments were well designed, so I was able to learn a lot :)

I would like to ask a specific question about the dropout method in an unsupervised setting.

And i checked the reply that you used the transformers package dropout method in a recent issue.

However, if the random seed is fixed, the same input pair will generate a different hidden representation only if a particular method for generating the dropout mask is used, but it is not clearly understood that this part was implemented using standard dropout. 

The code uses the default value (0.1) when defining the model with transformers without modifying the dropout. I wonder if the representation generated when the same input is simply encoded twice can be viewed as an output generated by controlling the dropout differently.

Could you please explain a little more in detail? 

Additionally, I am curious how you fixed the randomness of the corresponding part in the code during the p=0.1, fixed 0.1 experiment of 'table3', and proceeded with the experiment.

Thanks 🤗

**Comment by gaotianyu1350** [comment]
Hi,

The random seed is set at the beginning of the training, which means that every time we apply dropout on a sentence, the mask could be different. The randomness is controlled by keeping the same random seed (it's mostly for initialization).
