### ISSUE TITLE
Dynamically adjust the weight of MLM loss according to the number of training steps?

### ISSUE THREAD

**Issue by YJiangcm** [princeton-nlp/SimCSE#129]
Hi, thanks for your excellent work! 
I just wonder how should I modify your code to dynamically adjust the weight of MLM loss based on the number of training steps? For example, the weight of MLM loss decays as training progresses. Thx.

**Comment by gaotianyu1350** [comment]
You can check this line: https://github.com/princeton-nlp/SimCSE/blob/30b08875a39d0e89d71f17c57bd0dcc18e7c2f15/simcse/models.py#L219
