### ISSUE TITLE
Is there any class imbalance problem in loss calculation ?

### ISSUE THREAD

**Issue by gaoisbest** [princeton-nlp/SimCSE#130]
Thanks for your excellent work.

May be a stupid question, or  it is not a question. I just wonder that for a sample A in batch, since "take a cross-entropy objective with in-batch negatives", take unsupervised scenario as an example, there is one positive sample and (batch size -1) negative samples ? So, will it raises  class imbalance problem ? 

Correct me if I think wrong, thanks a lot.

**Comment by gaotianyu1350** [comment]
Hi,

This is not a "classification" problem, and each time the positive sample is different, so there is no "imbalance problem".

**Comment by gaoisbest** [comment]
> Hi,
> 
> This is not a "classification" problem, and each time the positive sample is different, so there is no "imbalance problem".

Ok, thanks.  For a sample A in batch, take unsupervised scenario as an example, there is one positive sample and (batch size -1) negative samples, is this right ?

**Comment by gaotianyu1350** [comment]
Yes that is correct.
