### ISSUE TITLE
Question about avg_first_last pooling

### ISSUE THREAD

**Issue by qishibo** [princeton-nlp/SimCSE#133]
https://github.com/princeton-nlp/SimCSE/blob/main/simcse/models.py#L72-L76

![image](https://user-images.githubusercontent.com/5136418/147336453-0078848e-c2f3-4c67-9bfd-101c35ef1701.png)

`avg_first_last`should be the mean of the first and last layers，but `hidden_states[0]` is the input embedding, `hidden_states[1]`is the first layer output, should't it be `first_hidden = hidden_states[1]`??

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for pointing this out! You are right that 0-index is the embedding layer and it has been fixed now. Though it does not affect our results in the paper since they all use CLS or last layer average.
