### ISSUE TITLE
环境的要求

### ISSUE THREAD

**Issue by EEEasonlove** [princeton-nlp/SimCSE#138]
我想知道对于transformers的版本要求是什么，pytorch我使用的是1.7.1版本，但是我在使用SimCSE库时会报错：ImportError: cannot import name 'AutoModel' from 'transformers' (unknown location)，我最初认为是pytorch的原因，但是我尝试了pytorch不同的版本还是会出现无法import name 'AutoModel'的问题

**Comment by gaotianyu1350** [comment]
Hi please use `transformers==4.2.1`, which is included in the requirements.txt

**Comment by EEEasonlove** [comment]
thanks , I was the one who overlooked the requirements.txt
