### ISSUE TITLE
Issue regarding installation

### ISSUE THREAD

**Issue by tanik4u** [princeton-nlp/SimCSE#142]
I was trying to install 'SimCSE' using the following steps:
(i.)  pip install simcse
(ii.) from simcse import SimCSE
after this command I got the error like below:
**"from: can't read /var/mail/simcse"**

Please help resolving this error.

**Comment by gaotianyu1350** [comment]
Hi,

Can you provide more error messages? It seems like a machine-specific issue. 

Ps. you can also directly clone the code and install from the code.
