### ISSUE TITLE
vocab_file none

### ISSUE THREAD

**Issue by ustbliubo2014** [princeton-nlp/SimCSE#143]
s/gpt2/tokenization_gpt2.py", line 179, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType
I finetune model in my dataset

**Comment by gaotianyu1350** [comment]
It seems that you didn't specify the pre-trained models? Can you share the script you were using?
