### ISSUE TITLE
I'm curious about the meaning of "hard negative" in the thesis.

### ISSUE THREAD

**Issue by fspanda** [princeton-nlp/SimCSE#154]
I read the thesis very interestingly.

I have a question for you.
Are you saying that the meaning of hard negative used in the thesis is "clearly negative" or is it used to mean "indistinguishable negative"?

Generally, it is used in the second sense, but after reading the thesis, I think you used it in the first sense.

**Comment by gaotianyu1350** [comment]
Hi,

Here it is just clear negative. But compared to the in-batch negatives, it is more "indistinguishable".

**Comment by fspanda** [comment]
Thank you for answer :)
