### ISSUE TITLE
question about "cls_before_pooler" option

### ISSUE THREAD

**Issue by ddobokki** [princeton-nlp/SimCSE#159]
hello! i have some question

in README.md, cls_before_pooler arguments is expained

- cls_before_pooler: Use the representation of [CLS] token without the extra linear+activation. If you use unsupervised SimCSE, you should take this option.

but in "run_unsup_example.sh", it take "cls" option 

is it just mistake? or used in experiment?

in simple experiment using korean PLM, take cls_before_pooler option get more good scores

and thank you!

**Comment by gaotianyu1350** [comment]
Hi,

In the unsupervised setting, we train the model with the CLS representation and evaluate the model with the representation before CLS. It is found to the best on English STS. However the gap is not very large and it could vary on different datasets or languages.

**Comment by ddobokki** [comment]
thank you!! I got it! Thanks for the good explanation! 👍
