### ISSUE TITLE
句子嵌入用于聚类

### ISSUE THREAD

**Issue by stronglily** [princeton-nlp/SimCSE#16]
作者您好：
       感谢您杰出的工作并把它开源出来。关于用预训练模型SimCSE编码获得的句子嵌入，我有一些问题向您请教：
       SimCSE获得的句子嵌入是否适合聚类任务呢？我尝试将SimCSE预训练模型用于FewRel数据集，并将编码得到的句子嵌入直接使用k-means算法进行聚类，但是聚类效果并不好，是否是编码向量太过相似而不够有区分度呢？还是不适用于文本聚类任务？

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for your interest in our work! So the question is whether SimCSE can be applied to sentence clustering. In general universal sentence embeddings (like ours) are good tools for sentence clustering. In the case of relation extraction, however, you may need extra efforts. The challenge in relation extraction is that the model needs to attend to the two entities, and universal sentence embeddings haven't learned that during training. I suggest you further fine-tune the model on the dataset or at least training an extra mapping on the dataset.

**Comment by zpppy** [comment]
> 作者您好：
> 感谢您杰出的工作并把它开源出来。关于用预训练模型SimCSE编码获得的句子嵌入，我有一些问题向您请教：
> SimCSE获得的句子嵌入是否适合聚类任务呢？我尝试将SimCSE预训练模型用于FewRel数据集，并将编码得到的句子嵌入直接使用k-means算法进行聚类，但是聚类效果并不好，是否是编码向量太过相似而不够有区分度呢？还是不适用于文本聚类任务？

I encounter the same problem。have you found some solution？
