### ISSUE TITLE
When I replace the model to Huggingface model, the speed of encode becomes too slow.

### ISSUE THREAD

**Issue by AlfredLiu6** [princeton-nlp/SimCSE#161]
When i replace your sup-simcse-bert-base-uncased into bert-base-uncased from huggingface.co, the speed of encode becomes too slow and keeps warning me "Some weights of the model checkpoint at .. were not used when initializing ..". Then I tried other pre-trained model in huggingface, the problem still exists. I would appreciate it a lot if you could help me solve this problem.

**Comment by gaotianyu1350** [comment]
It seems to be a Huggingface package problem. Maybe refer to their issue board/manual?

**Comment by AlfredLiu6** [comment]
> 

Thanks a lot, I have solved this problem.
