### ISSUE TITLE
Loss function calculation

### ISSUE THREAD

**Issue by natuhvnh** [princeton-nlp/SimCSE#164]
Hi, I have a question about the loss function calculation:
![Screenshot from 2022-05-05 12-10-12](https://user-images.githubusercontent.com/46572402/166866641-e48867a1-df38-4164-9185-c3f529eb5c83.png)
It means that we treat x(i) and x(j) similar to x(i) and its contradiction hypotheses ?
If yes, the loss function will not work well in case x(i) has many entialment hypothesis in the datasets and few of those appear in the mini-batch ?

**Comment by gaotianyu1350** [comment]
Hi,

In this form, xi+ is the entailment of xi. Can you elaborate more on "few of those appear in the mini-batch"?

**Comment by natuhvnh** [comment]
I mean that somehow hj+ is similar to hi+ (both are entailment of hi. But here hj+ is in the denominator, dose it effect the performance?

**Comment by gaotianyu1350** [comment]
Hi,

Hj+ is not the entailment sentence for hi (it is the entailment for hj). It is supposed to be different from hi.
