### ISSUE TITLE
finetune on IMDB dataset

### ISSUE THREAD

**Issue by Bin199** [princeton-nlp/SimCSE#165]
Hello! Glad to see your excellent work! I retrained unsup simcse on my device following readme document and finetuned it on imdb dataset to  improve the performance of sentiment classification. I also converted simcse to huggingface format after training the simcse. But when I load simcse when finetuning on imdb, I got the following error:
![1](https://user-images.githubusercontent.com/51829876/167057922-41065e25-62bb-4ca1-b3d4-14b437c3f924.png)
I have no idea about this. Could you point out what mistakes I made. Thanks a lot.

**Comment by gaotianyu1350** [comment]
It seems that you are using a different type of layer norm (layer norm's parameters should be layer norm.weight/bias, not gamma/beta), can you check whether everything is consistent between train and fine-tune?

**Comment by Bin199** [comment]
thanks a lot! I will check it.
