### ISSUE TITLE
Could not download the evaluation dataset.

### ISSUE THREAD

**Issue by shizhediao** [princeton-nlp/SimCSE#17]
When I was running  
`cd SentEval/data/downstream/;
bash get_transfer_data.bash
 `
I met: Failed to connect to ixa-svn.ehu.eus port 443: Connection timed out

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for the feedback! We found that the link provided by SentEval is unstable. Now the link is updated and you can check it out by pulling the latest commit.

**Comment by shizhediao** [comment]
> Hi,
> 
> Thanks for the feedback! We found that the link provided by SentEval is unstable. Now the link is updated and you can check it out by pulling the latest commit.

Thanks for your reply! Is it normal to see the prompts like below? 
![image](https://user-images.githubusercontent.com/18120087/116763252-c0e05e00-aa4f-11eb-9527-7df0441ae757.png)

**Comment by gaotianyu1350** [comment]
Yes I think it means everything works well.

**Comment by shizhediao** [comment]
Thanks a lot!
