### ISSUE TITLE
the use of hard_neg_weight

### ISSUE THREAD

**Issue by VictorMatt01** [princeton-nlp/SimCSE#171]
So this question is about the algorithm when it uses 3 sentences as input:
In the code on github the following "weight is used" when computing the final cos_sim score, but apperantly this score is 0.
I can't really find an explanation for it in the paper and i was wondering how the cos_sim would change if the weight is changed (both in positive and negative direction)
<img width="1224" alt="Screenshot 2022-05-15 at 17 48 43" src="https://user-images.githubusercontent.com/32751657/168481655-d6931380-08ac-451e-8a31-4115f6323d24.png">

**Comment by gaotianyu1350** [comment]
Here hard_negative_weight is the **log** of the hard negative weight (alpha in Table 7).

**Comment by Golovneva** [comment]
I guess I have the same question, what's the point of having summands that you multiply by 0? Like `[0.0] * (cos_sim.size(-1) - z1_z3_cos.size(-1))` . Wont's this `weights` tensor always boil down to just  `[z3_weight]`?

**Comment by gaotianyu1350** [comment]
[0.0] * x will create an array of size x with all values as 0.
