### ISSUE TITLE
fine tune sup-SimCSE

### ISSUE THREAD

**Issue by DanHuang752** [princeton-nlp/SimCSE#173]
Hi,

Thanks for the great work! I would like to fine tune sup-SimCSE by my own dataset. Can I set 'model_name_or_path' in run_sup_example.sh to princeton-nlp/sup-simcse-bert-base-uncased, set train_file to my own training data to  fine tune sup-SimCSE ? Thanks in advance!

**Comment by gaotianyu1350** [comment]
Hi,

Yes you can do so!

**Comment by DanHuang752** [comment]
Thanks for the quick reply!
