### ISSUE TITLE
CLTrainer evaluate， char-level input

### ISSUE THREAD

**Issue by bujiahao** [princeton-nlp/SimCSE#175]
In the SimCSE.simcse.trainers.py
the 106th line, " sentences = [' '.join(s) for s in batch]  "
When evaluate ， the code will convert a word (e.g. "eye") to a char ( e.g. "e","y","e")
why？

**Comment by gaotianyu1350** [comment]
Hi,

This is the SentEval format. Here each s in batch is a list of word, e.g., ["I", "have", "a", "pen", "."]. This operation will concatenate them back to a string sentence, "I have a pen .".

**Comment by bujiahao** [comment]
Thanks for the reply!
