### ISSUE TITLE
The dev Spearman is not correspond to the test Spearman for supervised model

### ISSUE THREAD

**Issue by YJiangcm** [princeton-nlp/SimCSE#177]
![image](https://user-images.githubusercontent.com/70904956/170641666-180e9b2b-0a5e-4ee5-9853-25a1fb4f8550.png)
Here shows that the eval_stsb_spearman and the eval_sickr_spearman of the current checkpoint are 0.8417 and 0.8118, respectively. Then I end the training and use evaluation.py to evaluate this checkpoint. However, the stsb_spearman and sickr_spearman on dev changed, as the below picture shows. This phenomenon only shows on supervised model but not unsupversied models. Would you mind explaining this? thanks a lot.

![1653632285(1)](https://user-images.githubusercontent.com/70904956/170642048-77191715-adf6-40b6-976f-2cc92e133943.png)

**Comment by YJiangcm** [comment]
I set "pooler_type" to cls both training and testing supervised simcse-bert-base-uncased.

**Comment by gaotianyu1350** [comment]
Hi,

Before using the evaluate.py, you should convert the model to the hugging face format (in the readme).
