### ISSUE TITLE
Why not use the pooler and the lm head initialized from the pretrained model?

### ISSUE THREAD

**Issue by Doragd** [princeton-nlp/SimCSE#179]
Hi, 
I noticed there are a pooler layer and an LM head that were newly initialized.
Why not use the weight from the pre-trained model to initialize them?

https://github.com/princeton-nlp/SimCSE/blob/5005c3daab99cb9f6ff92c526ab751079a169826/simcse/models.py#L281
https://github.com/princeton-nlp/SimCSE/blob/5005c3daab99cb9f6ff92c526ab751079a169826/simcse/models.py#L284

**Comment by gaotianyu1350** [comment]
Hi,

The BERT pooler layer was trained with the "next sentence prediction" task, which actually doesn't help with the sentence embedding task (we observed that in our preliminary experiments). So we just re-initialize it for clean setting.

**Comment by Doragd** [comment]
Thanks~
