### ISSUE TITLE
"scipy>=1.5.4,<1.6",

### ISSUE THREAD

**Issue by shon-otmazgin** [princeton-nlp/SimCSE#180]
can you update the setup file to support newer version of scipy and numpy? currently there is a problem to install it on py38 and only working with py37.

py38 is necessary run with apple silicone.

**Comment by gaotianyu1350** [comment]
Hi I updated the requirement to just using the latest. You can also just specify the version you want when you install.

**Comment by shon-otmazgin** [comment]
Hello, @gaotianyu1350
still when installing using pip (PyPi) the requirement for scipy>=1.5.4,<1.6 is there

Shon
