### ISSUE TITLE
No module named 'datasets'

### ISSUE THREAD

**Issue by yiyiyi3124** [princeton-nlp/SimCSE#181]
train.py: line 11:
`from datasets import load_dataset`

`Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
`

**Comment by yiyiyi3124** [comment]
train.py line 307:
`    if extension == "txt":
        extension = "text"
    if extension == "csv":
        datasets = load_dataset(extension, data_files=data_files, cache_dir="./data/", delimiter="\t" if "tsv" in data_args.train_file else ",")
    else:
        datasets = load_dataset(extension, data_files=data_files, cache_dir="./data/")`

I suppose it should be 
`elif extension == "csv"` ?

**Comment by gaotianyu1350** [comment]
Hi,

The datasets package is in our dependency. You can also just manually install it by `pip install datasets`.
