### ISSUE TITLE
No module named prettytable

### ISSUE THREAD

**Issue by sundavid2002** [princeton-nlp/SimCSE#185]
I downloaded the SimCSE folder and tried training a supervised roBERTa model in Python. I was able to perform all the steps up to running the evaluation.py file without error. However, when I tried running the evaluation.py file, I was told I needed a module named prettytable b/c evaluation.py uses it on line 6. I installed pretty table by executing "pip install prettytable" , but running evaluation.py again still returned the same message. What's going on? Do I need to install a specific version?

**Comment by sundavid2002** [comment]
*I downloaded the SimCSE folder in this post by clicking "Download zip" under "Code"

**Comment by gaotianyu1350** [comment]
Hi,

Can you post the exact error message here? Thanks!

**Comment by sundavid2002** [comment]
Traceback (most recent call last):
  File "/Users/davidsun/Downloads/SimCSE/evaluation.py", line 6, in <module>
    import prettytable
ImportError: No module named prettytable

**Comment by sundavid2002** [comment]
Traceback (most recent call last):
  File "/Users/davidsun/Downloads/SimCSE/evaluation.py", line 6, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable

**Comment by gaotianyu1350** [comment]
Hi,

This should be able to address by `pip install prettytable`.

**Comment by sundavid2002** [comment]
I no longer need help w/ this issue
