### ISSUE TITLE
SimCSE reproduction effect fluctuates

### ISSUE THREAD

**Issue by luoda888** [princeton-nlp/SimCSE#19]
excellent work!
I take the liberty of offering some ideas about the details of the experiment.
1. Different downstream task datasets rely on MLM tasks for further pre-training, and the training weights of MLM tasks need to be finely adjusted to fit into the multi-task learning framework. Is it possible to provide an ablation experiment that eliminates DAPT (MLM task)?
2. The downstream tasks in paper act on unsupervised inference tasks, and the baselines for comparison are algorithms such as Bert-whiting and Bert-flow. Can the work of SimCSE be defined as a new paradigm for unsupervised learning data enhancement in NLP? Or will this provide a whole new approach to pre-training?
3. Based on 2, have you considered the effect of contrast sentences on FineTune in classification, named entity recognition, and reading comprehension tasks?
Thanks reply!

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for your suggestions for the experiments! We haven't tried SimCSE in pre-training yet, but it is promising to try it out as a pre-training objective or combine it with other pre-training methods.
