### ISSUE TITLE
wget: Command not found

### ISSUE THREAD

**Issue by sundavid2002** [princeton-nlp/SimCSE#192]
I'm trying to train SimCSE in a virtual environment (w/ python 3.7.0) I tried to run the download_wiki.sh file, but I got an error message saying "/Users/davidsun/Downloads/SimCSE/data/download_wiki.sh: line 1: wget: command not found" This error persisted even after I installed wget using pip. What should I do?

**Comment by dchenhe** [comment]
wget is a Linux command, you may use “sudo apt-get install wget” （for ubuntu and debian）or "sudo yum -y install wget" (for centos) to install wget for your operation system

**Comment by sundavid2002** [comment]
I'm sorry, but I don't have access to a Linux computer where I have sudo permissions. Can this repo be run on a non-Linux OS?

**Comment by dchenhe** [comment]
Actually, you can just download the wiki dataset by yourself, instead of using wget command. if you don't have linux os, i recommend you to use colab to run the repo, google offers you an simple Linux-os platform and some free gpu computational resources. Hope that will work :)

**Comment by gaotianyu1350** [comment]
Hi, 

This repo is only tested in a linux environment and it seems that you are using a Mac environment. The downloading command can be executed manually (see `download_wiki.sh` for the dataset link).
