### ISSUE TITLE
Question about model convergence

### ISSUE THREAD

**Issue by Jessica-jia** [princeton-nlp/SimCSE#193]
How can I tell if the model is converging or not, and is the value of the loss function indicative? I trained on my own dataset and the loss of each iteration is around 5.0, is this correct?
Thanks to the author for sharing the code!

**Comment by gaotianyu1350** [comment]
Hi,

Loss around 5.0 seems to be too high. Usually for unsupervised datasets the loss should converge to almost 0; for supervised ones it should also be pretty low.
