### ISSUE TITLE
When inference hint:newly initialized: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']

### ISSUE THREAD

**Issue by Chucy2020** [princeton-nlp/SimCSE#196]
![image](https://user-images.githubusercontent.com/73978694/185178840-d54643ae-2c94-40f7-bde0-c4998a71b121.png)
请问我该如何解决这个问题？

**Comment by gaotianyu1350** [comment]
It seems that you forgot to convert the models before evaluating them. Please check out `convert models` section and `evaluation` section in README.
