### ISSUE TITLE
The model I want to use was added only after transfomer 4.2.1, what should I do in this case?

### ISSUE THREAD

**Issue by jweihe** [princeton-nlp/SimCSE#199]
thank you for your great work！but if i don't use transformer=4.2.1,The code will report an error “cannot import name '_model_unwrap' from 'transformers.trainer'“，could you tell me how to solve this case？thanks a lot~

**Comment by gaotianyu1350** [comment]
Hi,

In this case you can upgrade your transformers. Our code should also work for later transformers (unless there is some API change then you need to modify our code accordingly)
