### ISSUE TITLE
Thank you for the coming top-conference paper. I can not understand this part of the picture in paper. Thank you again.

### ISSUE THREAD

**Issue by guotong1988** [princeton-nlp/SimCSE#2]
![image](https://user-images.githubusercontent.com/4702353/115326769-6974ff00-a1c0-11eb-90e0-40c38b38a9dd.png)

**Comment by gaotianyu1350** [comment]
Hi,

Probably Section 3 better explains the model. In short, the unsupervised SimCSE predicts the input sentence itself (solid line) among in-batch negatives (dashed lines). And for the input sentence, we take two different embeddings with different dropout mask.

**Comment by zhengyanzhao1997** [comment]
您好高天，想问下在有监督的方法中对于每一个对于输入句子，你们是否仍然采用了具有不同dorpout mask的两个不同的embedding。那么在计算loss时 我理解每一个陈述句子产生的embedding都会对应两个由alignment产生的positive embedding 对吗
