### ISSUE TITLE
Got a Better Result?

### ISSUE THREAD

**Issue by 2hip3ng** [princeton-nlp/SimCSE#204]
I reproduced the experiment based on bert-base-uncased. And I didnot change any parameter. The result is 
![image](https://user-images.githubusercontent.com/38064349/192243213-292be8e0-51b4-4610-af2c-ff66630aaf73.png)
The paper is 
![image](https://user-images.githubusercontent.com/38064349/192243378-1ab96e91-268e-4310-9388-ddd91ef34f36.png)

The experiment is done on GPU V100 * 4. It seems to imporve a lot.

**Comment by gaotianyu1350** [comment]
Hi,

I believe you are looking at the DEV set. Our README has instructions on evaluating on the test set. Though the results could still vary based on different hardware and random seeds.

**Comment by 2hip3ng** [comment]
Hi,
it's Dev set. Thanks~
