### ISSUE TITLE
ImportError: scipy.special._ufuncs_cxx does not export expected C variable _export_expit

### ISSUE THREAD

**Issue by krrish-v** [princeton-nlp/SimCSE#206]
Error occurred while running on Google Colab

Code :

      from simcse import SimCSE

Error:

            ---------------------------------------------------------------------------
        
        ImportError                               Traceback (most recent call last)
        
        [<ipython-input-23-5f2276f4dfdf>](https://localhost:8080/#) in <module>
        ----> 1 from simcse import SimCSE
              2 
              3 #model = SimCSE("princeton-nlp/sup-simcse-bert-base-uncased")
        
        9 frames
        
        [/usr/local/lib/python3.7/dist-packages/simcse/__init__.py](https://localhost:8080/#) in <module>
        ----> 1 from .tool import SimCSE
        
        [/usr/local/lib/python3.7/dist-packages/simcse/tool.py](https://localhost:8080/#) in <module>
              7 import transformers
              8 from transformers import AutoModel, AutoTokenizer
        ----> 9 from sklearn.metrics.pairwise import cosine_similarity
             10 from sklearn.preprocessing import normalize
             11 from typing import List, Dict, Tuple, Type, Union
        
        [/usr/local/lib/python3.7/dist-packages/sklearn/__init__.py](https://localhost:8080/#) in <module>
             80     from . import _distributor_init  # noqa: F401
             81     from . import __check_build  # noqa: F401
        ---> 82     from .base import clone
             83     from .utils._show_versions import show_versions
             84 
        
        [/usr/local/lib/python3.7/dist-packages/sklearn/base.py](https://localhost:8080/#) in <module>
             15 from . import __version__
             16 from ._config import get_config
        ---> 17 from .utils import _IS_32BIT
             18 from .utils._tags import (
             19     _DEFAULT_TAGS,
        
        [/usr/local/lib/python3.7/dist-packages/sklearn/utils/__init__.py](https://localhost:8080/#) in <module>
             26 from ..exceptions import DataConversionWarning
             27 from .deprecation import deprecated
        ---> 28 from .fixes import np_version, parse_version
             29 from ._estimator_html_repr import estimator_html_repr
             30 from .validation import (
        
        [/usr/local/lib/python3.7/dist-packages/sklearn/utils/fixes.py](https://localhost:8080/#) in <module>
             18 import scipy.sparse as sp
             19 import scipy
        ---> 20 import scipy.stats
             21 from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
             22 import threadpoolctl
        
        [/usr/local/lib/python3.7/dist-packages/scipy/stats/__init__.py](https://localhost:8080/#) in <module>
            439 """
            440 
        --> 441 from .stats import *
            442 from .distributions import *
            443 from .morestats import *
        
        [/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py](https://localhost:8080/#) in <module>
             41 import scipy.special as special
             42 from scipy import linalg
        ---> 43 from . import distributions
             44 from . import mstats_basic
             45 from ._stats_mstats_common import (_find_repeats, linregress, theilslopes,
        
        [/usr/local/lib/python3.7/dist-packages/scipy/stats/distributions.py](https://localhost:8080/#) in <module>
              8 from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
              9 
        ---> 10 from . import _continuous_distns
             11 from . import _discrete_distns
             12 
        
        [/usr/local/lib/python3.7/dist-packages/scipy/stats/_continuous_distns.py](https://localhost:8080/#) in <module>
             20 import scipy.special._ufuncs as scu
             21 from scipy._lib._util import _lazyselect, _lazywhere
        ---> 22 from . import _stats
             23 from ._rvs_sampling import rvs_ratio_uniforms
             24 from ._tukeylambda_stats import (tukeylambda_variance as _tlvar,
        
        _stats.pyx in init scipy.stats._stats()
        
        cython_special.pyx in init scipy.special.cython_special()
        
        ImportError: scipy.special._ufuncs_cxx does not export expected C variable _export_expit
        
        
        ---------------------------------------------------------------------------
        NOTE: If your import is failing due to a missing package, you can
        manually install dependencies using either !pip or !apt.
        
        To view examples of installing some common dependencies, click the
        "Open Examples" button below.
        ---------------------------------------------------------------------------

**Comment by gaotianyu1350** [comment]
Hi,

Maybe try installing the scipy version as specified in requirement.txt?

**Comment by krrish-v** [comment]
It worked, there was a error in other used library

**Comment by qiyuxiao248** [comment]
I have a same error. How did you work?

**Comment by qiyuxiao248** [comment]
> It worked, there was a error in other used library

I have a same error. How did you work?
