### ISSUE TITLE
The results of the evaluation phase are not exactly in line with yours

### ISSUE THREAD

**Issue by Moximixi** [princeton-nlp/SimCSE#208]
The command is exactly as the following example, only the model_name_or_path is changed
```shell
python evaluation.py \
    --model_name_or_path princeton-nlp/sup-simcse-bert-base-uncased \
    --pooler cls \
    --task_set sts \
    --mode test
```
The rightmost column is the result of my Evaluation, why some results are the same and some are different?
![image](https://user-images.githubusercontent.com/32200567/195273675-22f17826-8246-4296-b9ff-4ae5bfbe90ec.png)

**Comment by gaotianyu1350** [comment]
Hi,

For the unsupervised model, you should use `--pooler cls_before_pooler`.  Please read our README for what pooler to use for each model.
