### ISSUE TITLE
Invalid tensor shape

### ISSUE THREAD

**Issue by peregilk** [princeton-nlp/SimCSE#211]
I keep getting the following error at the end of the first epoch:
"RuntimeError: Input tensor at index 1 has invalid shape [22, 44], but expected [22, 46]". This happens on a custom dataset. However, the dataset is thoroughly cleaned and should be valid. 

The error happens in: comm.py, line 231

Any idea what might be causing this?

**Comment by peregilk** [comment]
Deleting the last line in the dataset actually fixed the error in my case.

**Comment by epiphany711** [comment]
Do you know the reason of this problem? I met the similar mistake, and I don't know how to fix it. The dataset I used was wiki1m_for_simcse.txt

**Comment by haoliutj** [comment]
I have the same issue, deleting the last line does not fix my error. Wondering if anyone has better solutions?

"comm.py", line 235, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Input tensor at index 3 has invalid shape [32, 32], but expected [32, 34]"

**Comment by Dicer-Zz** [comment]
I meet the same issue for my custom dataset. Can anyone give some suggestion？

**Comment by Dicer-Zz** [comment]
I found the issue has been solved in #148 . In my case, using only single GPU is working in the unsupervised setting.

**Comment by haoliutj** [comment]
I solved by running the scripts with multiple GPU. the issue is that I was running the script for single gpu on  4 gpu cards that cause the shape errors. I

**Comment by gaotianyu1350** [comment]
Thanks @haoliutj @Dicer-Zz  for answering this! This is likely caused by running the single gpu script on multiple GPUs. Please use the corresponding script for different number of GPUs.
