### ISSUE TITLE
what's the purpose of cl_init

### ISSUE THREAD

**Issue by lihuiliullh** [princeton-nlp/SimCSE#215]
May I know what this part of code does? Is the pooler in cl_init the random dropout in your paper?

![image](https://user-images.githubusercontent.com/53407011/202587493-7fa507ff-b656-4238-94b4-37961133ca14.png)

**Comment by gaotianyu1350** [comment]
Hi, this is just an init function for the contrastive learning class. The dropout is the standard dropout within the Transformer. Pooler here is just the last layer MLP or average pooler (depending on what type of pooler you choose).
