### ISSUE TITLE
Can't Install on Mac M1

### ISSUE THREAD

**Issue by shawnjhenry** [princeton-nlp/SimCSE#217]
Hi,

I can't install SimCSE on my macbook pro because the version of scipy used as a dependency can't be installed on on M1, I think because it doesn't support ARM.  Would it be possible to to change the scipy dependency to a newer version that does, or is there another workaround?

Thanks,
Shawn

**Comment by gaotianyu1350** [comment]
Hi,

The scipy package should only be required during evaluation, so I believe you can still run the training part. I have no experience building an environment on M1 so sorry that I couldn't offer more help 😭

**Comment by 0ddAstronaut** [comment]
I encounter the same problem while using a 64-bit Power PC :(
