### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by lywang76** [princeton-nlp/SimCSE#218]
Hello, I follow your run_unsup_example.sh to train SimCSE.

I got the following errors in SentEval. Can you give me a guide how to fix it?![image](https://user-images.githubusercontent.com/41125918/206464608-e9e1e58c-dccf-4315-96fe-072681f05bb2.png)

**Comment by PKU-Fgx** [comment]
i found the same problem, have you already solved it?

**Comment by gaotianyu1350** [comment]
It seems that the python version might be too new for the code calling `inspect`. Maybe try Python < 3.9?

**Comment by fstermann** [comment]
I had the same issue, even with Python 3.8. Changing `inspect.getargspec` to `inspect.getfullargspec` should solve the issue.
