### ISSUE TITLE
what are the negative samples if removing the hard negative? (train with supervised verison)

### ISSUE THREAD

**Issue by Rachel-Yeah-Lee** [princeton-nlp/SimCSE#221]
Hi, I follow your supervised example, but remove the hard negative from the dataset,
In this may, where does the negative sample come from? Does it take the other '**sent0**'s or '**sent1**'s in the same batch as the negative sample? 
Would you give me some instructions? thanks a lot!

**Comment by wuxiangli91** [comment]
> Hi, I follow your supervised example, but remove the hard negative from the dataset, In this may, where does the negative sample come from? Does it take the other '**sent0**'s or '**sent1**'s in the same batch as the negative sample? Would you give me some instructions? thanks a lot!

I think the the negative samples are from other examples  in the batch , ie In-batch-negative

**Comment by Rachel-Yeah-Lee** [comment]
Thanks for @wuxiangli91's reply!
Do you mean that if I have a batch, size = 64,  it will have 63 negative samples for each input sentence? or do you thank it will have 126 negative samples? Since there are sentence pairs in the batch.

**Comment by gaotianyu1350** [comment]
Hi, in our current implementation, there will be 63 negatives.
