### ISSUE TITLE
What huggingface/transformers version is this compatible with?

### ISSUE THREAD

**Issue by bruel-gabrielsson** [princeton-nlp/SimCSE#223]
Hi! Great work! What huggingface/transformers version is this compatible with? Would be very grateful for your input!

**Comment by jeongwoopark0514** [comment]
I am running this in conda env with python 3.9 and transformer 4.2.1. There seems to be no problem!

**Comment by gaotianyu1350** [comment]
Transformers 4.2.1 should work! (as suggested in the requirements.txt file)
