### ISSUE TITLE
Uniformity and Alignment Code & Normalizing

### ISSUE THREAD

**Issue by bruel-gabrielsson** [princeton-nlp/SimCSE#225]
Hey! Would you be able to provide some code for the Uniformity and Alignment metrics? Because I don't see you normalizing any embeddings during training -- do you do that after training only as you compute the metric? 

Thanks!

**Comment by gaotianyu1350** [comment]
Hi,

We followed the original paper's code and did normalize for that evaluation. In our training we use cosine similarity, which also normalizes the embeddings.
