### ISSUE TITLE
pip simcse 问题

### ISSUE THREAD

**Issue by Reset-aa** [princeton-nlp/SimCSE#233]
请问这是什么原因？Model name 'princeton-nlp/sup-simcse-bert-base-uncased' was not found in tokenizers model name list

**Comment by gaotianyu1350** [comment]
It's unclear why this happens. Can you provide a bit more context? This model is on Huggingface [hub](https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased) and you should be able to download it.
