### ISSUE TITLE
Question about how did paper preprocess dataset

### ISSUE THREAD

**Issue by Lim-Sung-Jun** [princeton-nlp/SimCSE#236]
I am writing to inquire about the preprocessing of the ParaNMT-50M dataset for use with your SimCSE model.

As you may know, the ParaNMT-50M dataset consists of source sentences, paraphrases, and similarity scores. I am particularly interested in adapting your SimCSE model for contrastive learning with the ParaNMT-50M dataset. However, I could not find explicit details in your paper about how you preprocessed the dataset for this purpose.

I would be grateful if you could provide some insights or guidelines on the following:

How did you create positive and negative samples from the dataset? Specifically, did you use similarity score thresholds, or any other strategies, to identify positive and negative pairs?
Were there any specific cleaning, filtering, or augmentation steps you employed to ensure high-quality paraphrases and negative samples?
Did you experiment with different hard negative mining strategies for the ParaNMT-50M dataset? If so, could you share your findings or recommendations?

**Comment by gaotianyu1350** [comment]
For ParaNMT, we simply used their paraphrase pairs and there is no additional filtering or processing. We also didn't use any hard negatives and we simply trained on in-batch negatives.

**Comment by Lim-Sung-Jun** [comment]
> For ParaNMT, we simply used their paraphrase pairs and there is no additional filtering or processing. We also didn't use any hard negatives and we simply trained on in-batch negatives.

thanks 👍 

what about the other datasets? like QQP and Flickr30k

**Comment by Lim-Sung-Jun** [comment]
Your assistance has had a good impact on my understanding, and I truly appreciate your efforts. 
I will ask you other questions through github.

Thank you :)



-----Original Message-----

**Comment by Lim-Sung-Jun** [comment]
> For ParaNMT, we simply used their paraphrase pairs and there is no additional filtering or processing. We also didn't use any hard negatives and we simply trained on in-batch negatives.

+ In the case of Flickr30k, captions are not suitable for entailment because they are annotated for pictures and not for entailment. what do you think about this?

**Comment by gaotianyu1350** [comment]
Hi,

For all datasets other than the NLI datasets, we only use the positive pairs and simple in-batch negatives.

**Comment by Lim-Sung-Jun** [comment]
> Hi,
> 
> For all datasets other than the NLI datasets, we only use the positive pairs and simple in-batch negatives.

thank you!

have a good day~

**Comment by Lim-Sung-Jun** [comment]
Dear Tianyu Gao,

I have a question regarding the QQP dataset and the supervised datasets you have created.

In the case of the QQP dataset, did you use the "is_duplicate" column with a value of 1 to indicate positive samples? If this is correct, then there are 149,263 positive samples. However, in the paper, the dataset size is mentioned to be 134k. Could you please explain this discrepancy?

Additionally, if possible, could you provide the three supervised datasets you have created?

Thank you for your time and assistance. I look forward to hearing from you soon.

Best regards,

Sungjun Lim


-----Original Message-----

**Comment by Lim-Sung-Jun** [comment]
I have a question regarding the QQP dataset and the supervised datasets you have created.

In the case of the QQP dataset, did you use the "is_duplicate" column with a value of 1 to indicate positive samples? If this is correct, then there are 149,263 positive samples. However, in the paper, the dataset size is mentioned to be 134k. Could you please explain this discrepancy?

**Comment by gaotianyu1350** [comment]
Yes we used the `is_duplicate`=1 columns. We are not sure why there is a discrepancy in the numbers (maybe due to different versions of datasets).
