### ISSUE TITLE
Cannot install transformers==4.2.1

### ISSUE THREAD

**Issue by namin-an** [princeton-nlp/SimCSE#239]
I cannot install the required transformer version. The below errors are shown.

![image](https://user-images.githubusercontent.com/71120750/232357050-2822e3df-7e99-43b2-94c5-73f0e775d45b.png)

If I use the latest version, ImportErrors appear as well. 

![image](https://user-images.githubusercontent.com/71120750/232357238-aa20c93f-03ac-4b64-8344-e3c2fd58cb08.png)

**Comment by clustydusty** [comment]
Hi,
I have the same problem. Can you tell me how you solved it?
