### ISSUE TITLE
where is the module 'datasets' in train.py

### ISSUE THREAD

**Issue by CheungZeeCn** [princeton-nlp/SimCSE#24]
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'

Thanks

**Comment by gaotianyu1350** [comment]
Hi,

`datasets` is a dependency package (in `requirements.txt`). You should directly install it by `pip install -r requirements.txt` or `pip install datasets`.

**Comment by CheungZeeCn** [comment]
thanks :)
