### ISSUE TITLE
How to train your model to better fit SentEval

### ISSUE THREAD

**Issue by ZBWpro** [princeton-nlp/SimCSE#241]
Hi~ 

SentEval requires users to implement a function called "batcher(params, batch)".

When it comes to STS tasks, the parameter "batch" of the batcher function only contains one sentence of a certain sentence pair.

This may cause conflicts, as your model typically requires the entire sentence pair as input.

If you convert sentences of a pair to embeddings one by one, it means you will need to call forward twice. This behavior is poorly supported by DDP.

**Comment by gaotianyu1350** [comment]
Hi,

Sorry about the late replyl. I'm not sure I totally follow. SentEval is only used for eval, thus it shouldn't affect DDP.

**Comment by ZBWpro** [comment]
Thanks for your reply, I found that I could solve this problem by introducing an extra encoding function into the class and calling it several times in forward.
