### ISSUE TITLE
Support python 3.10 (current Google Colab runtime)

### ISSUE THREAD

**Issue by mocobeta** [princeton-nlp/SimCSE#248]
I found `simcse` package can't be installed on Google Colab.

The problem is that the current Google Colab runtime is Python 3.10 that does not support old SciPy and NumPy.

```sh
$ python -V
Python 3.10.12

$ pip install simcse
...
Collecting scipy<1.6,>=1.5.4 (from simcse)
  Using cached scipy-1.5.4.tar.gz (25.2 MB)
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I don't see any problems with Python 3.9, so I guess something was changed in Python 3.10.
I'm wondering if it is possible to upgrade SciPy and NumPy dependencies so that users can run SimCSE on the latest python (and Google Colab).

**Comment by gaotianyu1350** [comment]
Hi,

You can upgrade scipy and numpy to the latest version according to your need. I believe those won't affect the main functions of SimCSE.

**Comment by Norahaltriri** [comment]
the same issue I have

**Comment by xiayouran** [comment]
directly install it from code，in `setup.py` ：

![image](https://github.com/princeton-nlp/SimCSE/assets/45480822/4b4dda2c-030e-41b6-99c4-183cecc9f4ac)

then `python setup.py install`
