### ISSUE TITLE
求roberta中文预训练模型

### ISSUE THREAD

**Issue by XiangwenNing** [princeton-nlp/SimCSE#256]
您好，请问，我用https://huggingface.co/hfl/chinese-roberta-wwm-ext/tree/main 这个预训练模型跑完了simcse，但是推理的时候报错了。
求一份可以推理成功的roberta中文预训练模型，谢谢！
![d2ed5c7ff9e8f060f656bfabef0730f5](https://github.com/princeton-nlp/SimCSE/assets/26280121/ac0e1b2e-994a-4024-9479-0e5de473538a)

**Comment by yaoxingcheng** [comment]
从报错信息来看是因为没有找到vocab文件导致的，有没有查看一下输出文件夹里面存不存在vocab.txt?
