### ISSUE TITLE
Huggingface datasets version 1.2.1 raises ConnectionError in chinese region

### ISSUE THREAD

**Issue by Majokiki** [princeton-nlp/SimCSE#26]
Hi🥰

```
ConnectionError: Couldn't reach https://raw.githubusercontent.com/huggingface/datasets/1.2.1/datasets/text/text.py
```

I encountered a connection error as above

and figured out that Huggingface had released new versions of datasets (datasets>=1.3.0) to make the library work in offline mode, see [this](https://github.com/huggingface/datasets/issues/1771). 

I solved it by upgrading the `datasets` to version 1.3.0, but wonder whether it could result in anything incompatible.

Thanks.

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for reporting this. I think upgrading the `datasets` package should be fine and everything should be compatible. Let me know if this is not the case.
