### ISSUE TITLE
About model format conversion

### ISSUE THREAD

**Issue by fzxxg** [princeton-nlp/SimCSE#262]
I didn’t reproduce using your code, can I use your evaluation file? But I noticed that your model format needs to be converted. If I don’t convert it, it can still run successfully, but what impact will this have? The following is the code I executed for the evaluation file:
  python evaluation.py \
    --model_name_or_path  bert-base-uncased-sts \
    --pooler cls_before_pooler \
    --task_set sts/transfer \
    --mode test

**Comment by fzxxg** [comment]
I only saved the BERT parameters in the model.

**Comment by seanswyi** [comment]
I believe the output format is safetensors. There should be any actual impact.

**Comment by gaotianyu1350** [comment]
Hi @fzxxg , if you use our training code and don't convert it, the checkpoint won't be able to perform as well as the paper reported; however, if you are evaluating other models, it should be fine (as long as the inference for those models are strictly the same as how they are supposed to be used.
