### ISSUE TITLE
　Why add two sentences in prepare_features?

### ISSUE THREAD

**Issue by FinalFlowers** [princeton-nlp/SimCSE#263]

**Comment by FinalFlowers** [comment]
https://github.com/princeton-nlp/SimCSE/blob/main/train.py#L419C13-L419C13

**Comment by gaotianyu1350** [comment]
Hi, here `examples[sent0_cname]` and `examples[sent1_cname]` are both lists, so it is a concatenation of two lists instead of two strings.

**Comment by FinalFlowers** [comment]
> Hi, here `examples[sent0_cname]` and `examples[sent1_cname]` are both lists, so it is a concatenation of two lists instead of two strings.

Get~ Thank you~
