### ISSUE TITLE
TypeError: object of type 'IndexFlatIP' has no len()

### ISSUE THREAD

**Issue by Maydaytyh** [princeton-nlp/SimCSE#268]
Hi, I trained `roberta-large` with my own data by using `run_sup_example.sh`.  But when I build index for senteced and use `model.search`, I encountered the error. The building process has no problem, the error is in `model.search`.
```
/site-packages/simcse/tool.py", line 64, in encode
    total_batch = len(sentence) // batch_size + (1 if len(sentence) % batch_size > 0 else 0)
TypeError: object of type 'IndexFlatIP' has no len()
```

**Comment by Maydaytyh** [comment]
I modify the default value of `use_faiss` to True, then it works. Maybe something wrong

**Comment by gaotianyu1350** [comment]
Hi Maydaytyh,

Thanks for spotting our the problem! I'll look into it
