### ISSUE TITLE
model = SimCSE("princeton-nlp/sup-simcse-bert-base-uncased")调用

### ISSUE THREAD

**Issue by ArchimedesLiu** [princeton-nlp/SimCSE#269]
调用时会出现报错：Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
请问有无好的解决方案？

**Comment by gaotianyu1350** [comment]
Hi,

It seems to be an Internet connection error. One work around is to find our model on https://huggingface.co and download it manually.

**Comment by Maydaytyh** [comment]
you can solve it by `export HF_ENDPOINT=https://hf-mirror.com`.

**Comment by ArchimedesLiu** [comment]
Thank you very much for your help. A very strange phenomenon is that I will fail to access by China Mobile's network, but can access it under China Telecom or China Unicom's network. In the end, I chose to download the model by https://huggingface.co.

**Comment by ArchimedesLiu** [comment]
@
