### ISSUE TITLE
the format of NLI dataset for training

### ISSUE THREAD

**Issue by La-SilverLand** [princeton-nlp/SimCSE#27]
how do you format the input for the supervised training by NLI data?
it is not straightforward from the code for this question, and it is not explicitely described in the paper
since your pooler_output is reshaped to (bs, num_sent, hidden)
for the triplet set {xi, xi_positive, xi_negtive}, is it formated like this ? 
[CLS] some text tokens for xi [SEP]
[CLS] some text tokens for xi_positive [SEP]
[CLS] some text tokens for xi_negative [SEP]

and several triplets above form the batch ?

thanks

**Comment by gaotianyu1350** [comment]
Hi,

You are right about the format.
