### ISSUE TITLE
Can I load saved index to GPU?

### ISSUE THREAD

**Issue by Maydaytyh** [princeton-nlp/SimCSE#270]
Hi, due to the large number of sentences, it's not possible to save them all at once. Therefore, I've split them into 10 smaller files. Is it possible to load the index onto the GPU when loading? Loading into memory might still result in an overflow.

**Comment by gaotianyu1350** [comment]
Hi,

Usually if it doesn't fit in CPU memory it won't fit in the GPU memory either. I would suggest exploring some of the index compression options in [faiss](https://github.com/facebookresearch/faiss)
