### ISSUE TITLE
Can I replace the base model with longformer? Is it a simple replacement or does the code also need to be changed? Thank you for your answer.

### ISSUE THREAD

**Issue by Struggle-lsl** [princeton-nlp/SimCSE#271]
Can I replace the base model with longformer? Is it a simple replacement or does the code also need to be changed? Thank you for your answer.

**Comment by gaotianyu1350** [comment]
Hi,

I do believe some minor code change is needed, as it only supports bert or Roberta for now. But since everything is based on Huggingface, the change should be minimal. You can just follow the bert examples in the code and edit it to be long former accordingly.

**Comment by lsl200032** [comment]
> Hi,
> 
> I do believe some minor code change is needed, as it only supports bert or Roberta for now. But since everything is based on Huggingface, the change should be minimal. You can just follow the bert examples in the code and edit it to be long former accordingly.

Hello, longformer is based on robert. My understanding is that you can directly replace the model file without changing the code.
