### ISSUE TITLE
AttributeError: 'OurTrainingArguments' object has no attribute 'distributed_state'

### ISSUE THREAD

**Issue by zongxindu** [princeton-nlp/SimCSE#275]
'OurTrainingArguments' object has no attribute 'distributed_state'
  File "/public/duzx/project/Path2Vec/SimCSE/train.py", line 548, in main
    trainer = CLTrainer(
  File "/public/duzx/project/Path2Vec/SimCSE/train.py", line 600, in <module>
    main()
AttributeError: 'OurTrainingArguments' object has no attribute 'distributed_state'

**Comment by gaotianyu1350** [comment]
Hi,

It seems that you are using an incomparable transformers version?
