### ISSUE TITLE
setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (750,) + inhomogeneous part.

### ISSUE THREAD

**Issue by JYru** [princeton-nlp/SimCSE#276]
报错：setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (750,) + inhomogeneous part.

**Comment by xiayouran** [comment]
maybe the `numpy` version is too advanced.
`pip install numpy==1.23.0
`
