### ISSUE TITLE
drpout

### ISSUE THREAD

**Issue by riyajatar37003** [princeton-nlp/SimCSE#279]
Hi,

where exactly dropout is being applied ? can anyone point to code/file.

thanks

**Comment by yaoxingcheng** [comment]
Hi,

We reuse the dropouts implemented by Huggingface's transformers, which are applied to attention blocks and hidden states of each transformer layer. See [modeling_bert.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bert/modeling_bert.py)  and [modeling_roberta.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/roberta/modeling_roberta.py) from transformers' source code for details.

**Comment by riyajatar37003** [comment]
Thanks got it.
