### ISSUE TITLE
when I run evaluation.py, the spearman is unusually low

### ISSUE THREAD

**Issue by UGUESS-lzx** [princeton-nlp/SimCSE#283]
Thanks for your hard work!
Here I have a question, when I use the code below, I got a very strange result
python evaluation.py     --model_name_or_path /home/bert-base-uncased/     --pooler cls     --task_set sts     --mode test
I got a 
![image](https://github.com/user-attachments/assets/5265caa4-4cc9-4152-8860-373253a62fce)
It can be found that the spearman is unusually low, what might be the reason for this？
Thanks a lot!

**Comment by gaotianyu1350** [comment]
Hi, the vanilla BERT with cls does have a very bad performance on STS. Can you try one of the SimCSE models or try BERT with avg to see if it matches the paper performance?

**Comment by gaotianyu1350** [comment]
I believe the number reported in the paper is first/last average, which would correspond to `--avg_first_last`

**Comment by UGUESS-lzx** [comment]
Ok, I got it. Thank you very much!
