### ISSUE TITLE
Sampling Negatives for Sentiment Analysis

### ISSUE THREAD

**Issue by mel-ugaddan** [princeton-nlp/SimCSE#288]
Hello,

Your work is interesting. I want to reproduce your work. Just want to ask, how do you sample negatives ($h^-_j$) for _Sentiment Analysis_ task for datasets like _MR, SST2 and MPQA_. Do you like randomly sample from the training dataset where the _label_ of the sample text is not the same as the _sample text_ ($h_i$). Also, do you applied the same hyperparameter ( `k` )/`batch_size=512`,
based from the formula 

Thank you

**Comment by gaotianyu1350** [comment]
Hi, we do not train on those datasets (the unsupervised SimCSE only uses the wikipedia data and the supervised one only uses the NLI data). We do not directly train on any of the datasets tested.

**Comment by mel-ugaddan** [comment]
Ohhh I see, I understand now. Thank you for the reply
