### ISSUE TITLE
关于模型用于embedding相似度计算会出现奇怪case的问题

### ISSUE THREAD

**Issue by zpppy** [princeton-nlp/SimCSE#29]
比如q="第一次蒸花馍还可以"，simcse召回的top2“花呗第一次可以借多少”、“第一次见你你一笑”，而bertflow召回的是“第一次蒸糕”、“蒸馍”，感觉更合理些。还有不少这种case，有些字面完全不相似的也被召回了(而中等字面相似的反而没被召回)。总体感觉字面相似度比较高的能被准确召回，但对于字面相似度中等或不相似的，就容易出现奇怪的case。

是不是dropout生成正样本的方式没有bertflow可控，容易训偏？？

**Comment by gaotianyu1350** [comment]
Hi,

For now our released SimCSE checkpoints do not support languages other than English. You can find a Chinese version of SimCSE from the readme section "SimCSE Elsewhere".
