### ISSUE TITLE
For unsupervised SimCSE, the core improvement reason is different-dropout-masks, am I right?

### ISSUE THREAD

**Issue by guotong1988** [princeton-nlp/SimCSE#3]
Thank you very much!

**Comment by gaotianyu1350** [comment]
Hi,

We think the core improvement comes from the "negative sampling" part of the contrastive loss: it makes the embedding space more uniform. However, if not taking the different dropout masks, it will lead to collapsing solution (the alignment will degrade by a large margin). Our Figure 2 gives a sense about why unsupervised simcse works.
