### ISSUE TITLE
Question about Figure4 in the paper 

### ISSUE THREAD

**Issue by fantingwei** [princeton-nlp/SimCSE#30]
Thanks for your hard work!
Here i have a question:According to Figure 4 in the paper,you say "Compared to all the baseline models,both unsupervised and supervised SimCSE better distinguish sentence pairs with different levels of similarities".what is the criteria?mean or variance?
Thanks again!

**Comment by yaoxingcheng** [comment]
Thanks for your attention to our work.
The assertion based on Figure 4. is a qualitative one, which doesn't strictly depend on any quantitative criteria like mean or variance. It's easy to tell from Figure 4. that compared with vanilla BERT, SimCSE shows a more scattered distribution accross different levels of similarities (the mean of distribution in different similarity levels are scattered), and compared with BERT-flow, SimCSE retains a high confidence (low variance) on sentence pairs with high similarities. Those are all features desirable for sentence embeddings but not observed in baseline models.

**Comment by fantingwei** [comment]
Thank you for your answer!
