### ISSUE TITLE
MLP layer in the models.py

### ISSUE THREAD

**Issue by cn-boop** [princeton-nlp/SimCSE#31]
Hi,

I am confused why mlp layer in the models.py doesn't change the dim of the vectors. (when pool_type=cls), so what is the function of this layer?

**Comment by gaotianyu1350** [comment]
Hi,

You don't need "changing the dim of the vectors" for an MLP layer to work. Here the MLP layer is just for adding some transformation over the original CL representation so it might suit our need better.

**Comment by zpppy** [comment]
I add dropout in MLP layer in chinese dataset，and result is more good.

**Comment by EEEasonlove** [comment]
> I add dropout in MLP layer in chinese dataset，and result is more good.

Hello, I would like to add dropout to the MLP layer to improve the performance of the model, but I found that dropout is already used in the source code, so I would like to ask you how to add dropout to the MLP layer.
