### ISSUE TITLE
Confusion in run_unsup_examples.sh

### ISSUE THREAD

**Issue by fantingwei** [princeton-nlp/SimCSE#32]
hi,
I have another queation:when running run_unsup_example.sh with '--do_train True'，it still goes directly to evaluate.
Thans a lot!

**Comment by gaotianyu1350** [comment]
Hi,

Can you share the full command you use?

**Comment by fantingwei** [comment]
Hi,
I made a mistake and now it's fixed!
Sorry for wasting your time and thanks again!
