### ISSUE TITLE
Avg pooling and cls results in unsupervised models

### ISSUE THREAD

**Issue by cn-boop** [princeton-nlp/SimCSE#33]
Hi, I run the experiments with avg pooling and cls, separately in the unsupervised setting, but i find that the result of cls exceeds the results of avg pooling by almost 18.0%.
Could you explain this phenomenon?
Thanks.

**Comment by gaotianyu1350** [comment]
Hi,

Do you mean you train the model with avg pooling and cls, or use our checkpoints and evaluate our model with different pooling methods?

**Comment by cn-boop** [comment]
yes ，but the results of cls and avg pooling are very different，do you know why？

发自我的iPhone

**Comment by cn-boop** [comment]
﻿yes ，but the results of cls and avg pooling are very different，do you know why？

发自我的iPhone

**Comment by yaoxingcheng** [comment]
It looks like the pooling methods for training and evaluation are not consistent. Are you using cls pooling in evaluation for models trained with avg pooling?
