### ISSUE TITLE
Why we need gather all embeddings if using distributed training?

### ISSUE THREAD

**Issue by Doragd** [princeton-nlp/SimCSE#34]
Please forgive me for asking a simple question, why do we need to do this? If we don’t do this, what are the consequences?

**Comment by yaoxingcheng** [comment]
Thanks for your attention. During ablation study we've found that the batch size, i.e. number of sampled negative instances, will effect the quality of sentence embedding. If we do not gather embeddings accross different devices,  number of negative instances won't be scaled up by distributed training.

**Comment by Doragd** [comment]
if num_sent < 3 (there is no supervised negative instances, only in-batch negative instances), when distributed training, do we need gather all embeddings ?

**Comment by yaoxingcheng** [comment]
Yes, I think it's necessary to gather embeddings for both supervised and unsupervised negatives.

**Comment by Doragd** [comment]
Thanks for your kind and quick reply.
