### ISSUE TITLE
Question about Figure 2 in the paper

### ISSUE THREAD

**Issue by Sosuke115** [princeton-nlp/SimCSE#35]
Thank you for your hard work.

I have a question.
I am not sure what the point of training sentence embeddings in extreme cases (no dropout and fixed 0.1) is.
I think that the same [CLS] embeddings would be output from BERT and the cosine similarity would always be 1.0.

**Comment by gaotianyu1350** [comment]
Yeah you are right. In the case of no dropout and fixed 0.1, the cosine similarity of the positive pairs will always be 1, however, the cosine similarities of negative pairs still vary and it is still meaningful to train the model in this way.

**Comment by Sosuke115** [comment]
Thank you for your reply, I understand.
