### ISSUE TITLE
load model error

### ISSUE THREAD

**Issue by lijinze9456yy000** [princeton-nlp/SimCSE#39]
hello, I load your SimCSE model.
model = SimCSE("princeton-nlp/sup-simcse-bert-base-uncased")
Error:ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

**Comment by gaotianyu1350** [comment]
Hi,

I just tried it out and it worked for me. According to the error message, it seems to be a connection error. Can you check your network and try again?
