### ISSUE TITLE
the results of bert-flow and bert-whitening is obviously lower than original results

### ISSUE THREAD

**Issue by bojone** [princeton-nlp/SimCSE#4]
For example, the spearman of STS12 of bert_base-flow and bert_base-whitening in your Table 6 is 58.40 and 57.83, but the actual corresponding results in the paper of bert-flow and bert-whitening is 63.48 and 63.62

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for pointing this out! We talked about this in the paper that different works actually take different evaluation settings, and we elaborated different settings in Appendix B. In short, our work, following SBERT, takes the "all" setting, while BERT-flow and BERT-whitening take the "wmean" setting. See Table B.1 for metrics & settings used in different papers, Table B.2 for our reproduction results, and Table B.3 for comparison under the "wmean" setting.

**Comment by bojone** [comment]
okay. sorry for my negligence. actually a good job!
