### ISSUE TITLE
AutoTokenizer.from_pretrained Failed

### ISSUE THREAD

**Issue by hksskh** [princeton-nlp/SimCSE#42]
In the Model List, all models can be successfully loaded via the sample code in "Use SimCSE with Huggingface", except for two models "princeton-nlp/unsup-simcse-roberta-base" and "princeton-nlp/unsup-simcse-roberta-large". 

Traceback:
tokenizer = AutoTokenizer.from_pretrained(model_path)
return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs) 
...
with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Please let me know if anyone succeed in this.

**Comment by gaotianyu1350** [comment]
Hi, 

Thanks for reporting this! We have already fixed the problem now and you can try again!
