### ISSUE TITLE
Any Plans for Multilingual Versions?

### ISSUE THREAD

**Issue by zhongpeixiang** [princeton-nlp/SimCSE#44]
This is a great work and has many potential applications.

Are there any plans to support multilingual text? For example, adapting from mBERT?

Thanks,
Peixiang

**Comment by gaotianyu1350** [comment]
Hi Peixiang,

Thanks for your interest in our work! Currently, we do not have a plan for multilingual SimCSE, but since the algorithm should work on all the languages, feel free to try out our code on datasets with other languages!
