### ISSUE TITLE
is this should be distance?

### ISSUE THREAD

**Issue by qiuyu666** [princeton-nlp/SimCSE#46]
cosine(embeddings[0], embeddings[1]) is the  cosine similarities of  0 and 1,then 1-cosine should be called distance of 0 an 1?

##Calculate cosine similarities
##Cosine similarities are in [-1, 1]. Higher means more similar
cosine_sim_0_1 = 1 - cosine(embeddings[0], embeddings[1])
cosine_sim_0_2 = 1 - cosine(embeddings[0], embeddings[2])

print("Cosine similarity between \"%s\" and \"%s\" is: %.3f" % (texts[0], texts[1], cosine_sim_0_1))
print("Cosine similarity between \"%s\" and \"%s\" is: %.3f" % (texts[0], texts[2], cosine_sim_0_2))

**Comment by gaotianyu1350** [comment]
Hi,

`cosine` in scipy is 1 - cosine similarity, so we need to do 1 - `cosine` to get the cosine similarity.

**Comment by qiuyu666** [comment]
> Hi,
> 
> `cosine` in scipy is 1 - cosine similarity, so we need to do 1 - `cosine` to get the cosine similarity.


好的，了解了，谢谢~
