### ISSUE TITLE
unsup-robert-large train with batch_size=512 OOM

### ISSUE THREAD

**Issue by 1024er** [princeton-nlp/SimCSE#49]
Hi 

I tried unsup-robert-large train with batch_size=512, resulting in OOM on a single 3090 GPU
can you help me ?

<br class="Apple-interchange-newline">

**Comment by ScottishFold007** [comment]
> Hi
> 
> I tried unsup-robert-large train with batch_size=512, resulting in OOM on a single 3090 GPU
> can you help me ?

Please adjust the bz smaller, depending on the configuration of the graphics card, the amount of power to do

**Comment by gaotianyu1350** [comment]
Thanks @ScottishFold007 for pointing this out. @1024er you should try to reduce the batch size or use multiple GPUs (we have example scripts for running our code on multiple GPUs).
