### ISSUE TITLE
Implementation details of the dropout mask.

### ISSUE THREAD

**Issue by huhk-sysu** [princeton-nlp/SimCSE#5]
First, I appreciate your hard work.

I'm not sure about the "dropout mask" in Chapter 3. In the following words:

> feed the same input to the encoder twice by **applying different dropout masks**

Do you mean: "Simply feed the input to the encoder, and during training, the encoder will automatically apply different dropout mask (from `nn.dropout`) to the input"? The structure of BERT remains unchanged, and we don't need to manually create the mask, right?

**Comment by gaotianyu1350** [comment]
Hi,

Your understanding is correct. No extra change is needed over original BERT implementation. Simply forwarding the same sentence two times will give you two embeddings with different (internal) dropout masks.

**Comment by minmummax** [comment]
that's really thicking data augment method. LMAO
