### ISSUE TITLE
Why use devacc in test mode？

### ISSUE THREAD

**Issue by polarxjl** [princeton-nlp/SimCSE#50]
https://github.com/princeton-nlp/SimCSE/blob/main/evaluation.py#L196

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for pointing it out! It is indeed a bug and now it is fixed. It does not affect our internal code base for producing the results in the paper, so the numbers in the papers are still correct.

**Comment by polarxjl** [comment]
Thanks for your reply. Because the data size of test set and dev set in some datasets is different, can you rerun to provide TestACC? The above request is based on:
1. DevACC was used in your experiments.
2. TestACC was used in other baseline model experiments.

**Comment by gaotianyu1350** [comment]
Hi,

The numbers reported in the papers are test accuracy (we used a separate repo for experiments and that repo takes the correct code).

**Comment by polarxjl** [comment]
Thank you for your reply. I have no doubt about this.
