### ISSUE TITLE
About supervised SimCSE

### ISSUE THREAD

**Issue by cordeliazhu** [princeton-nlp/SimCSE#56]
Hi,

I would like to check if I want to get my own three sentences pair could I generator from two contrast sentences? (x,x,x-)

In this case, my understanding is that simCSE still works. 

Best

**Comment by gaotianyu1350** [comment]
Hi,

Yes, this should still work with SimCSE.

**Comment by MrRace** [comment]
@gaotianyu1350 If I just have two sentences  pari and its label which mean the pair same or not~ In the other way, I do not have `hard_ne`, how can I format the data for training supervised-SimCSE? Thanks a lot~
