### ISSUE TITLE
snli dataset in senteval

### ISSUE THREAD

**Issue by mmmmmeng** [princeton-nlp/SimCSE#57]
hello.i cant download the smi dataset by running the download_dataset.sh in senteval. is something wrong?

**Comment by gaotianyu1350** [comment]
Hi,

Can you paste the error message here?

**Comment by mmmmmeng** [comment]
thanks for your replying. no error message but just the snli data folder is empty after running the data loading shell. i solved this problem through senteval toolkit. thank you~
















At 2021-07-16 12:28:51, "Tianyu Gao" ***@***.***> wrote:

Hi,

Can you paste the error message here?
