### ISSUE TITLE
Will you open source the training code?

### ISSUE THREAD

**Issue by applenob** [princeton-nlp/SimCSE#6]
An excellent job! Will you open source the training code? Do you have any plan to train a Chinese or multi-language version model?

**Comment by gaotianyu1350** [comment]
Hi, thanks for your interest! We are now working on open-sourcing the training code and it will come out soon. 

About models on Chinese or other languages, we don't have the plan yet but this sounds interesting. Also feel free to try on other languages using our code (once we release it).

**Comment by applenob** [comment]
Thank you for your reply. Looking forward to it.
