### ISSUE TITLE
Question about the Pooler+MLP layer in code implementation

### ISSUE THREAD

**Issue by mrzhang11** [princeton-nlp/SimCSE#61]
Hi,

Firstly, thank the authors for sharing the nice work and code. 

I have a question about the code implementation of the modeling part. For the 'BertForCL' model, since self.bert (BertModel) already contains a BertPooler non-linear layer, I was wondering that why we need an additional MLP layer to simulate it? Should we initialize a BertModel without the BertPooler? 

And in the simcse_to_huggingface.py, the original BertPooler layer will be replaced by the MLP layer, is there any reason to do so rather than simply drop the MLP and keep the original BertPooler?

Thanks in advance!

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for your interest in our work! The reason is that we have also tried to use different poolers in our experiments, so for convenience, we separated it from the Huggingface's pooler. Although in the end we found that the original BERT pooler works well, we still kept it for extensibility.
