### ISSUE TITLE
An issue on running run_sup_example.sh

### ISSUE THREAD

**Issue by 14H034160212** [princeton-nlp/SimCSE#64]
Hi,

I got an issue when I run the `run_sup_example.sh` when I try to use distributed data parallel (multi-GPU). I did not have this issue when I switch it to single-GPU.

07/27/2021 22:19:53 - INFO - torch.distributed.distributed_c10d -   Waiting in store based barrier to initialize process group for rank: 3, key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00)
07/27/2021 22:19:53 - INFO - torch.distributed.distributed_c10d -   Waiting in store based barrier to initialize process group for rank: 2, key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00)
07/27/2021 22:19:53 - INFO - torch.distributed.distributed_c10d -   Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00)
07/27/2021 22:19:53 - INFO - torch.distributed.distributed_c10d -   Waiting in store based barrier to initialize process group for rank: 1, key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00)
 

![image](https://user-images.githubusercontent.com/23516191/127137806-084efa3e-5d64-4f32-8054-68ab60e1af10.png)

**Here is the scritpt that I am using.**

NUM_GPU=4
PORT_ID=$(expr $RANDOM + 1000)
export OMP_NUM_THREADS=8

python -m torch.distributed.launch --nproc_per_node $NUM_GPU --master_port $PORT_ID train.py \
    --model_name_or_path roberta-large \
    --train_file data/nli_for_simcse.csv \
    --output_dir result/my-sup-simcse-roberta-large \
    --num_train_epochs 3 \
    --per_device_train_batch_size 128 \
    --learning_rate 5e-5 \
    --max_seq_length 32 \
    --evaluation_strategy steps \
    --metric_for_best_model stsb_spearman \
    --load_best_model_at_end \
    --eval_steps 125 \
    --pooler_type cls \
    --overwrite_output_dir \
    --temp 0.05 \
    --do_train \
    --do_eval \
    --fp16 \
    "$@"

**Here is the environment that I am using.**

- transformers==4.2.1
- scipy==1.5.4
- datasets==1.2.1
- pandas==1.1.5
- scikit-learn==0.24.0
- prettytable==2.1.0
- gradio==2.2.3
- torch==1.9.0
- setuptools==49.3.0

**Comment by gaotianyu1350** [comment]
It seems to be an environment issue. You should check whether you have installed cuda and nccl correctly. Also, check whether you have 4 GPUs available to the script.

**Comment by 14H034160212** [comment]
Hi,

Thanks for your comment. I reinstall the torch using this command `pip install torch==1.7.1+cu110 -f https://download.pytorch.org/whl/torch_stable.html` to downgrade the version from 1.9.0 to 1.7.1 which is working now. You can see the first 4 GPUs are selected during the training. What if the first 4 GPUs have been allocated by other tasks, does the model can be training on the later 4 GPUs automatically?

![image](https://user-images.githubusercontent.com/23516191/127431379-4b676cd0-3f61-4c27-9d14-88c887ab5f0a.png)

**Comment by gaotianyu1350** [comment]
You can set GPUs by modifying the environment variable `CUDA_VISIBLE_DEVICES`.
