### ISSUE TITLE
use simcse for multiple sentence embedding in a document

### ISSUE THREAD

**Issue by nlpxxx** [princeton-nlp/SimCSE#65]
Hi,

thank you for sharing the code.
How can I use simcse to obtain multiple sentence embedding in a document? I want to use all sentence vectors to match the downstream task. 
D = [s1, s2, s3, ...]
What am I supposed to do?

**Comment by gaotianyu1350** [comment]
Hi,

You can refer to [our wiki](https://github.com/princeton-nlp/SimCSE/wiki) for the guidelines of using our API. You should be able to encode the document with only a few lines of python code.

**Comment by nlpxxx** [comment]
Hi,
i have read the guidelines, but i can only obtain a representation when I input the document, I want to acquire all sentence representations of the document using simcse API. If I split the document into sentences, it would seem to separate the semantic information from the full document.

**Comment by gaotianyu1350** [comment]
Hi,

Now we only support separately encoding the sentences in a document.

**Comment by nlpxxx** [comment]
> Hi,
> 
> Now we only support separately encoding the sentences in a document.

ok, thanks
