### ISSUE TITLE
How to add new sentence into index

### ISSUE THREAD

**Issue by OptimusMsc** [princeton-nlp/SimCSE#66]
We can build a index for a group of sentence in a list or a file, now I want to add a new sentence in to the old index, is there any way to fix this problem? Building a new index for the new sentence and all old sentences is very inefficient.

**Comment by OptimusMsc** [comment]
https://github.com/facebookresearch/faiss/wiki/Getting-started
Found the solution here.

**Comment by Uzay-G** [comment]
Could we get something to do this added to the library?

**Comment by Uzay-G** [comment]
#166
