### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 2; 47.46 GiB total capacity; 45.22 GiB already allocated; 605.25 MiB free; 45.68 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by 14H034160212** [princeton-nlp/SimCSE#67]
Hi,

I got the CUDA out of memory issue. I am running `run_sup_example.sh` on 4 GPUs (RTX 8000, each GPU has 48601MiB (48GB) memory) and I am using the `RoBERTa-large` and the hyperparameter I am using `batch size = 512`, `learning rate = 1e-5`. If 4 Nvidia 3090 GPUs can run the supervised SimCSE (large) why it cannot be running in RTX 8000 and each GPU has 48GB memory?

![image](https://user-images.githubusercontent.com/23516191/127438280-7f1060d2-ecb0-4686-8b01-0a442e02b5cf.png)

**Comment by gaotianyu1350** [comment]
Hi,

I see that you have more than 4 GPUs available. Please make sure that when you run the script, you properly set up the GPUs by using `CUDA_VISIBLE_DEVICES`. Also, make sure that the selected GPUs are not occupied by other programs.

**Comment by 14H034160212** [comment]
Thanks. One more question when I try to replicate the result from Sup. RoBERTa. I met the CUDA out of memory issue when I use batch size = 512. But it works when the batch size = 128. Does different batch size will produce much different results? 
![image](https://user-images.githubusercontent.com/23516191/127807308-e03cfc73-e4d1-40fe-8efc-f55fde28477e.png)

**Comment by gaotianyu1350** [comment]
Different batch sizes might make a significant difference if using the same learning rate and other hyperparameters.
