### ISSUE TITLE
How to draw the visualization map?

### ISSUE THREAD

**Issue by 14H034160212** [princeton-nlp/SimCSE#69]
Hi,

Does the porject provide the code to draw the visualization map from Figure 3 as the paper shown?
![Screenshot from 2021-08-03 15-28-19](https://user-images.githubusercontent.com/23516191/127953104-e4f44f41-8d62-4afc-b2ca-a399eed6174e.png)

Kind regards,
Qiming

**Comment by gaotianyu1350** [comment]
You can draw a similar figure by using matplotlib's `colorbar`.
