### ISSUE TITLE
请问模型就是完全使用bert本身有的dropout作为一种数据增强吗？ 

### ISSUE THREAD

**Issue by KeepGoingCSU** [princeton-nlp/SimCSE#70]
整个训练的正样本就是同一个句子过两次dropout_rate=0.1的bert吗？这样的话是不是在图像上也可以尝试啊，比如现在基于transformer的图片/视频contrastive learning

**Comment by gaotianyu1350** [comment]
Hi,

Yes, we simply send the same sentence twice to the encoder. It might also work for the images and feel free to try so!
