### ISSUE TITLE
请问下有中文版本的预训练模型嘛

### ISSUE THREAD

**Issue by ustcgcc** [princeton-nlp/SimCSE#73]
您好，很感谢你的开源工作。但是我想在中文上测试一下结果。我没找到开源的预训练好的模型，您能提供链接嘛

**Comment by gaotianyu1350** [comment]
你可以试试这个：https://github.com/bojone/SimCSE

**Comment by ScottishFold007** [comment]
@ustcgcc 我训练了也给有监督的版本，基于NLI、成语、诗歌文白翻译构成的三元组训练的，语义识别效果很好，https://drive.google.com/drive/folders/12CMquNFqxs5WWS7bgLJiYrasTPYQIxpH?usp=sharing
