### ISSUE TITLE
有监督部分和Sbert很像？

### ISSUE THREAD

**Issue by Tongjilibo** [princeton-nlp/SimCSE#74]
请教一下，simcse的源码中，感觉有监督部分就是和sentence bert的multiNegativeRankingLoss一致，是这么理解吗？并且有hard negatives的时候，我看weights是全0矩阵吗？

**Comment by gaotianyu1350** [comment]
Hi,

Yes, our contrastive loss is the same as the "multi negative ranking loss" in sentence BERT. Actually, that part of the sentence BERT only came out after the release of our work. The weights are indeed zero, because it's the "logarithm" of the weight (so the real weight would be 1).

**Comment by Tongjilibo** [comment]
Thanks a lot
