### ISSUE TITLE
AttributeError: 'CLTrainer' object has no attribute 'sharded_dpp'

### ISSUE THREAD

**Issue by enze5088** [princeton-nlp/SimCSE#75]
```
Traceback (most recent call last):
  File "train.py", line 585, in <module>
    main()
  File "train.py", line 549, in main
    train_result = trainer.train(model_path=model_path)
  File "/data2/simcse/trainers.py", line 568, in train
    if self.sharded_dpp:
AttributeError: 'CLTrainer' object has no attribute 'sharded_dpp'
Traceback (most recent call last):
  File "train.py", line 585, in <module>
    main()
  File "train.py", line 549, in main
    train_result = trainer.train(model_path=model_path)
  File "/data2/simcse/trainers.py", line 568, in train
    if self.sharded_dpp:
```
Is that sharded_dpp or sharded_ddp?
这里是 sharded_dpp还是sharded_ddp？
似乎是transformers版本不同造成的变量名称的差异。

**Comment by gaotianyu1350** [comment]
Hi,

The error might be due to the different versions of transformers. You can change the name directly to suit your transformers version or use our recommended version in `requirement.txt`.

**Comment by zhizhengyan** [comment]
这是因为版本的问题，SimCSE使用的transformers==4.2.1 高版本的transfomer已经把这个位置换成了sharded_ddp

具体可参考：https://huggingface.co/transformers/v4.2.2/_modules/transformers/trainer.html#Trainer
https://huggingface.co/transformers/v4.5.1/_modules/transformers/trainer.html#Trainer
4.2.1使用的是sharded_dpp
