### ISSUE TITLE
OSError: Can't load config for 'princeton-nlp/sup-simcse-bert-base-uncased'

### ISSUE THREAD

**Issue by missannas** [princeton-nlp/SimCSE#77]
您好，运行过程中遇到了OSError: Can't load config for 'princeton-nlp/sup-simcse-bert-base-uncased'，有完整下载链接吗，谢谢您

**Comment by gaotianyu1350** [comment]
Hi,

We just checked and the name should be correct. You can check whether your `transformers` version is the same as what we have in `requirement.txt`. You can also use [this link](https://huggingface.co/princeton-nlp/sup-simcse-bert-base-uncased/tree/main) for downloading the model.
