### ISSUE TITLE
low acc for the uploaded unsupervised models

### ISSUE THREAD

**Issue by leoozy** [princeton-nlp/SimCSE#80]
Hello, I tired the uploaded unsup-simcse-models. The evaluation scripts is:

model_path=princeton-nlp/unsup-simcse-bert-large-uncased
#python simcse_to_huggingface.py --path ${model_path}
python evaluation.py \
    --model_name_or_path  ${model_path} \
    --pooler cls \
    --task_set sts \
    --mode test \

My platform is:
GPU: NVIDIA A100
platform: Centos 8
other packages are install from the requirement: pip install -r requirements.txt 

But the acc is sigificantly low for the uploaded model compared with the given results in table. 

Here is some results;

princeton-nlp/unsup-simcse-bert-base-uncased:
![image](https://user-images.githubusercontent.com/26025961/130190742-801e0f24-ef07-469c-b95a-22e496d7b613.png)
princeton-nlp/unsup-simcse-bert-large-uncased
![image](https://user-images.githubusercontent.com/26025961/130191027-094971e7-63f2-4159-b7e7-c3f13b0fdfff.png)
princeton-nlp/unsup-simcse-roberta-base
![image](https://user-images.githubusercontent.com/26025961/130191203-19cf4851-b879-4587-adb9-80e9a19ba831.png)
princeton-nlp/unsup-simcse-roberta-large
![image](https://user-images.githubusercontent.com/26025961/130192418-d63b5fd7-1d58-4d99-b4e8-5beebab128f1.png)

**Comment by leoozy** [comment]
I found the problem. There are some bugs in my scripts.

**Comment by zyznull** [comment]
> I found the problem. There are some bugs in my scripts.

Hi, I have met the same problem, could you please share how do you solve this problem?

**Comment by keezen** [comment]
> > I found the problem. There are some bugs in my scripts.
> 
> Hi, I have met the same problem, could you please share how do you solve this problem?

Maybe you can try to set "pooler cls_before_pooler"?
