### ISSUE TITLE
SentEval Subj.subjective only contains 20 sentences 

### ISSUE THREAD

**Issue by PootieT** [princeton-nlp/SimCSE#84]
Hi! I recently found out if I run `SentEval/data/downstream/download_dataset.sh` you guys provided, the `SUBJ` dataset `subj.subjective` file contains only 20 sentences (as opposed to 5000 that `subj.objective` has). I hope this is not just a system error on my side, but if it is reproducible, the evaluation accuracy for SUBJ is consistently above 99%..

Here is the script I ran from `download_dataset.sh`:
```bash
wget https://huggingface.co/datasets/princeton-nlp/datasets-for-simcse/resolve/main/senteval.tar
tar xvf senteval.tar
```

**Comment by gaotianyu1350** [comment]
Hi,

Thanks for reporting this issue! It seems that the uploaded dataset is corrupted. Now the correct datasets are updated.

**Comment by PootieT** [comment]
Thank you!
