### ISSUE TITLE
关于有监督训练方法的一点疑问

### ISSUE THREAD

**Issue by zhengyanzhao1997** [princeton-nlp/SimCSE#9]
您好高天，想问下在有监督的方法中对于每一个对于输入句子，你们是否仍然采用了具有不同dorpout mask的两个不同的embedding。那么在计算loss时 我理解每一个陈述句子产生的embedding都会对应两个由alignment产生的positive embedding 对吗

**Comment by gaotianyu1350** [comment]
您好，在有监督场景下，标准的dropout仍然是打开的，但我们没有再对每个输入样本forward两次得到positive pair，而是直接用NLI数据中的entailment pair作positive pair。

**Comment by zhengyanzhao1997** [comment]
感谢你的解答

**Comment by liebkne** [comment]
那Fig 1b里的红圆圈和绿圆圈，为啥还是两个一对呢？

**Comment by gaotianyu1350** [comment]
因为每一组数据是由一个premise, 一个entailment的hypothesis和一个contradiction的hypothesis组成的。

**Comment by liebkne** [comment]
对啊。那不应该是绿-绿、绿-红这样？为什么是绿绿-绿绿、绿绿-红红？

**Comment by gaotianyu1350** [comment]
两个绿色的圈表示的sentence embedding，不是说有两个句子

**Comment by liebkne** [comment]
这样啊……因为`Different dropout masksin two forward passes`刚好写在两个圈上面。。明白了，谢谢。

**Comment by KRYSTALLJY** [comment]
所以对于有监督来说，只是对原始的bert模型加了attention dropout？

**Comment by gaotianyu1350** [comment]
我们所有的模型都是用的bert原始的dropout，包括hidden state dropout和attention dropout
