### ISSUE TITLE
Error while computing cosine similarity

### ISSUE THREAD

**Issue by gaurav-95** [princeton-nlp/SimCSE#91]
Hello! I get the following error when comparing one sentence vs many others using similarities = model.similarity(keyword, phrases)
the model loaded is model = SimCSE("princeton-nlp/sup-simcse-bert-base-uncased")

` ~\AppData\Roaming\Python\Python38\site-packages\simcse\tool.py in similarity(self, queries, keys, device)
    110 
    111         # returns an N*M similarity array
--> 112         similarities = cosine_similarity(query_vecs, key_vecs)
    113 
    114         if single_query:

~\anaconda3\lib\site-packages\sklearn\metrics\pairwise.py in cosine_similarity(X, Y, dense_output)
   1178     # to avoid recursive import
   1179 
-> 1180     X, Y = check_pairwise_arrays(X, Y)
   1181 
   1182     X_normalized = normalize(X, copy=True)

~\anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

~\anaconda3\lib\site-packages\sklearn\metrics\pairwise.py in check_pairwise_arrays(X, Y, precomputed, dtype, accept_sparse, force_all_finite, copy)
    147                         copy=copy, force_all_finite=force_all_finite,
    148                         estimator=estimator)
--> 149         Y = check_array(Y, accept_sparse=accept_sparse, dtype=dtype,
    150                         copy=copy, force_all_finite=force_all_finite,
    151                         estimator=estimator)

~\anaconda3\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

~\anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)
    671                     array = array.astype(dtype, casting="unsafe", copy=False)
    672                 else:
--> 673                     array = np.asarray(array, order=order, dtype=dtype)
    674             except ComplexWarning as complex_warning:
    675                 raise ValueError("Complex data not supported\n"

ValueError: could not convert string to float:`

**Comment by gaotianyu1350** [comment]
Hi,

Can you check what's the keyword and phrases here?

**Comment by gaurav-95** [comment]
I'm comparing news articles, keyword is a single news article and phrases is a list of other news articles.
ex:
keyword = "When Heat Waves, Wildfires and Drought Grip Oregon and Washington"
phrases = ["'An Experimental H.I.V. Vaccine Fails in Africa', 'An early build of Overwatch 2 will be used for Overwatch League in 2022'....]

I get this error on specfic articles. This time it was on:

 ValueError: could not convert string to float: '#AppleToo: employees organize and allege harassment and discrimination'

**Comment by gaurav-95** [comment]
ValueError: could not convert string to float: '$10 Billion in Student Debt Erased Under Biden, but Calls Grow for More'
ValueError: could not convert string to float: 'Barrett Avoids Slips at Confirmation Hearings'

These are 2 other articles it shows the error on.

**Comment by gaotianyu1350** [comment]
Hi,

It might be some special characters in the string. Can you try to delete those two articles and try again? If it works with those, then the issue comes from those two articles.

**Comment by gaurav-95** [comment]
I had the same feeling looking at the articles it gave errors on. But you can see the last article I mentioned in my previous message does not have any punctuation mark or special character.

'Barrett Avoids Slips at Confirmation Hearings'

 Still I face the same value error with this article as well.

**Comment by gaurav-95** [comment]
That solved the problem @oztalha, Looks like I'm supposed to pass input as a list, not a NumPy array.

--> 673 array = np.asarray(array, order=order, dtype=dtype)
674 except ComplexWarning as complex_warning:
675 raise ValueError("Complex data not supported\n"

This part of the error log should have made it obvious but here we are anyway. Thanks for the help!
