### ISSUE TITLE
Is the wiki data shuffled when training the unsupervised SimCSE?

### ISSUE THREAD

**Issue by YJiangcm** [princeton-nlp/SimCSE#93]
Thanks for your excellent job! I wonder if the wiki data is shuffled when training the unsupervised SimCSE. And if I want to train unsupervised SimCSE with unshuffled data, how should I do? Thx.

**Comment by gaotianyu1350** [comment]
Hi,

For all the data we take the shuffle during training. If you want to train with unshuffled data (I'm not sure why you want to do this), you can simply turn off the "shuffle" option in the data loader.
