### ISSUE TITLE
SimCSE 分类初始化相关

### ISSUE THREAD

**Issue by 520jefferson** [princeton-nlp/SimCSE#95]
如果采用simCSE进行初始化，训练query-reply 二分类任务(softmax作为损失)会有提升吗（之前是采用google的bert初始化的)？目前是正例稍多，负例少，试了focal loss没啥作用，不知道simCSE是否有提升

**Comment by gaotianyu1350** [comment]
Hi,

I think SimCSE could be helpful. Maybe try it out!
