### ISSUE TITLE
How do you collect the 1M Wiki data?

### ISSUE THREAD

**Issue by BaohaoLiao** [princeton-nlp/SimCSE#96]
Hi,

this is a really great paper. In your paper, you used 1M wiki data for unsupervised learning. May I ask how do you collect it? I wonder whether we need to make sure the wiki data is in the same domain of STS task. 

If possible, could you provide the script for it? Including the collecting and preprocessing scripts. 

Thank you in advance!

**Comment by gaotianyu1350** [comment]
Hi,

We simply take the Wikipedia dump and randomly sampled 1M sentences. We didn't do any filtering/selection here.

**Comment by BaohaoLiao** [comment]
I see. Thank you.
