### ISSUE TITLE
Is negative example shared within mini-batch?

### ISSUE THREAD

**Issue by sh0416** [princeton-nlp/SimCSE#98]
Hi, I wonder that the negative examples are shared when computing cosine similarity.

I think the broadcasting is not needed..
```
z1_z3_cos = cls.sim(z1.unsqueeze(1), z3.unsqueeze(0))
```

Also, could you give some commit id that reproduces the checkpoint you provided?

Thanks,

**Comment by sh0416** [comment]
```
z1_z3_cos = cls.sim(z1, z3).unsqueeze(-1)
```
Could be better, I think.

**Comment by gaotianyu1350** [comment]
Sorry I didn't get the question. Were you asking whether the negatives are shared within the batch? The answer is yes.

You should be able to reproduce our result by using the latest commit.
